### ISSUE TITLE
Error orrcur:  'NoneType' object is not iterable

### ISSUE THREAD

**Issue by duyvipsss** [ciuzaak/Claude-Telegram-Bot#11]
When I chat with Bard, The telegram bot returns the message  "'NoneType' object is not iterable". Please help me fix this problem. Thank you

**Comment by ciuzaak** [comment]
I believe the issue is an authentication error with Bard. Please double check that you have properly obtained authentication credentials by following these steps:

## Authentication
Go to https://bard.google.com/

- F12 for console
- Copy the values
  - Session: Go to Application → Cookies → `__Secure-1PSID`. Copy the value of that cookie.

**Don't forget the `.` at the end of `__Secure-1PSID`.**

**Comment by duyvipsss** [comment]
Thank you for your response. I have identified and resolved the issue. It seems that the problem was caused by the recent update to version 1.1.3 of the acheong08-Bard two days ago. After updating to version 1.1.3 myself, the problem was successfully resolved.
